services:
    phpbb.googleanalytics.listener:
        class: phpbb\googleanalytics\event\listener
        arguments:
            - @config
            - @controller.helper
        tags:
            - { name: event.listener }
